version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    # Adicione outros serviços aqui, como banco de dados
    # db:
    #   image: postgres:13
    #   environment:
    #     - POSTGRES_DB=email_editor
    #     - POSTGRES_USER=postgres
    #     - POSTGRES_PASSWORD=postgres
    #   volumes:
    #     - postgres_data:/var/lib/postgresql/data
    #   ports:
    #     - "5432:5432"

# volumes:
#   postgres_data:
